recipe_site/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from recipes.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('recipes/', include('recipes.urls')),
    path('profile/', include('users.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from .views import recipe_detail, recipe_list, category_list, category_recipes, add_recipe, edit_recipe

urlpatterns = [
    path('list/', recipe_list, name='recipe_list'),
    path('<int:recipe_id>/', recipe_detail, name='recipe_detail'),
    path('edit/<int:recipe_id>', edit_recipe, name='edit_recipe'),
    path('add/', add_recipe, name='add_recipe'),
    path('category/list', category_list, name='category_list'),
    path('category/<int:category_id>', category_recipes, name='category_recipes'),
]

users/urls.py
from django.urls import path, include

from .views import user_login, registration, user_page

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('', user_page, name='user_page'),
    path('registration/', registration, name='registration'),
    path('login/', user_login, name='login'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name='Название')

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'


class Recipe(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    cooking = models.TextField(verbose_name='Приготовление')
    cooking_time = models.PositiveSmallIntegerField(default=0, verbose_name='Время приготовления')
    image = models.ImageField(upload_to='images/', default='default.png', blank=True, verbose_name='Изображение')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор рецепта')
    products = models.TextField(verbose_name='Продукты', default='')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Категория')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'recipe'
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'

recipes/forms.py
from django import forms

from .models import Recipe, Category


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description', 'cooking', 'cooking_time', 'image', 'products', 'author']
        widgets = {
            'cooking': forms.Textarea(attrs={'rows': 6}),
        }

    category = forms.ModelChoiceField(queryset=Category.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = "Нет категории"

recipes/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Recipe, Category
from .forms import RecipeForm


def index(request):
    categories = Category.objects.all()
    recipes = Recipe.objects.order_by('?')[:6]
    return render(request, 'main_page/index.html', {'categories': categories, 'recipes': recipes})


def recipe_detail(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    return render(request, 'recipes/recipe_detail.html', {'recipe': recipe})


def category_recipes(request, category_id):
    recipes = Recipe.objects.filter(category_id=category_id)
    per_page = 6
    paginator = Paginator(recipes, per_page)
    page_number = request.GET.get('page')
    try:
        recipes_paginator = paginator.page(page_number)
    except PageNotAnInteger:
        recipes_paginator = paginator.page(1)
    except EmptyPage:
        recipes_paginator = paginator.page(paginator.num_pages)
    return render(request, 'recipes/recipe_list.html', {'recipes': recipes_paginator})


def recipe_list(request):
    recipes = Recipe.objects.order_by('id')
    per_page = 6
    paginator = Paginator(recipes, per_page)
    page_number = request.GET.get('page')
    try:
        recipes_paginator = paginator.page(page_number)
    except PageNotAnInteger:
        recipes_paginator = paginator.page(1)
    except EmptyPage:
        recipes_paginator = paginator.page(paginator.num_pages)
    return render(request, 'recipes/recipe_list.html', {'recipes': recipes_paginator})


def category_list(request):
    categories = Category.objects.all()
    return render(request, 'recipes/category_list.html', {'categories': categories})


def category_detail(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    return render(request, 'recipes/category_list.html', {'category': category})


@login_required
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            category = form.cleaned_data['category']
            recipe.category = category
            recipe.save()
            return redirect('recipe_list')
    else:
        form = RecipeForm()
    return render(request, 'recipes/add_recipe.html',
                  {'form': form})


@login_required
def edit_recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id)
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user
            category = form.cleaned_data['category']
            recipe.category = category
            recipe.save()
            return redirect('recipe_detail', recipe_id=recipe_id)
    else:
        form = RecipeForm(instance=recipe)
    return render(request, 'recipes/edit_recipe.html',
                  {'form': form, 'recipe': recipe})

recipes/templates/recipes/add_recipe.html
{% extends 'base.html' %}

{% block content %}
<h1>Добавить новый рецепт</h1>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
        {% if form.errors %}
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ field.label }}: {{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
    <button type="submit">Сохранить</button>
</form>
{% endblock %}

recipes/templates/recipes/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Категории{% endblock %}

{% block content %}
    <h1 class="d-flex justify-content-between">Рецепты по категориям</h1>
    <div class="d-flex justify-content-between">
        <div class="col-md-4 mt-3 mb-3">
            <div class="card">
        <ul class="list-group">
            {% for category in categories %}
            <li class="list-group-item">
                <a class="list-group-item list-group-item-action text-primary"
                   href="{% url 'category_recipes' category.id %}">
                   <b>{{ category.name }}</b>
                <span class="badge badge-primary badge-pill">{{ category.recipe_set.count }}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
            </div>
        </div>
    </div>
{% endblock %}

recipes/templates/recipes/edit_recipe.html
{% extends 'base.html' %}

{% block content %}
<h1>Редактирование рецепта</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if form.errors %}
        <ul>
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    {% endif %}

    <button type="submit">Обновить</button>
</form>
{% endblock %}

recipes/templates/recipes/recipe_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row d-flex justify-content-center">
    <div class="col-md-8 mt-3 mb-3">
        <div class="card">
            {% if recipe.image %}
                <img src="{{ recipe.image.url }}" class="card-img-top img-fluid" alt="{{ recipe.title }}">
            {% else %}
                <img src="{% static 'img/default.png' %}" class="card-img-top img-fluid" alt="{{ recipe.title }}">
            {% endif %}
            <div class="card-body d-flex flex-column justify-content-between">
                <h5 class="card-title">{{ recipe.title }}</h5>
                <p class="card-text">{{ recipe.description }}</p>
                <p class="card-text">Время приготовления: {{ recipe.cooking_time }} мин</p>
                <p class="card-text">Продукты:  {{ recipe.products }} </p>
                <p class="card-text">Приготовление: {{ recipe.cooking|linebreaks }}</p>

                {% if recipe.author == user or user.is_staff %}
                    <div class="col-4">
                        <a class="btn btn-outline-info" href="{% url 'edit_recipe' recipe.id %}">Редактировать рецепт</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

recipes/templates/recipes/recipe_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Рецепты{% endblock %}

{% block content %}
    <h1>Список рецептов</h1>

    <div class="row">
        {% for recipe in recipes %}
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    {% if recipe.image %}
                        <img src="{{ recipe.image.url }}" class="card-img-top" alt="{{ recipe.title }}">
                    {% else %}
                        <img src="{% static 'img/default.png' %}" class="card-img-top" alt="{{ recipe.title }}">
                    {% endif %}
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">{{ recipe.title }}</h5>
                        <p class="card-text">{{ recipe.description|truncatewords:20|linebreaks }}</p>
                        <p class="card-text">{{ recipe.category }}</p>
                        <p class="card-text">Время приготовления: {{ recipe.cooking_time }} мин</p>
                        <a href="{% url 'recipe_detail' recipe.id %}" class="btn btn-primary mt-auto">Подробнее</a>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="container">
              <div class="row">
                <div class="col-md-6 mb-5">
                  <div class="card">
                    <div class="card-body d-flex justify-content-center">
                      <p class="card-text text-primary"><b>Нет рецептов</b></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
    </div>
    {% include "pagination.html" with page=recipes %}
{% endblock %}